/** 以「我」为中心的关系图谱（节点间距 ≥140px，避免卡片重叠） */
const GRAPH_TEMPLATE = [
  // 父系直系 · 往上（单列）
  ["tier7p", "爸爸的爸爸的爸爸的爸爸的爸爸的爸爸的爸爸", "先祖父", 520, 40],
  ["tier6p", "爸爸的爸爸的爸爸的爸爸的爸爸的爸爸", "烈祖父", 520, 118],
  ["tier5p", "爸爸的爸爸的爸爸的爸爸的爸爸", "天祖父", 520, 196],
  ["tier4p", "爸爸的爸爸的爸爸的爸爸", "高祖父", 520, 274],
  ["tier3p", "爸爸的爸爸的爸爸", "曾祖父", 480, 352],
  ["tier3m", "爸爸的爸爸的爸爸的妈妈", "曾祖母", 620, 352],
  ["grandpaBrother", "爸爸的爸爸的哥哥", "伯祖父", 260, 430],
  ["grandpa", "爸爸的爸爸", "爷爷", 420, 430],
  ["grandma", "爸爸的妈妈", "奶奶", 620, 430],
  // 母系往上
  ["tier3mp", "妈妈的爸爸的爸爸", "外曾祖父", 780, 352],
  ["tier3mm", "妈妈的爸爸的妈妈", "外曾祖母", 960, 352],
  ["mgrandpa", "妈妈的爸爸", "外公", 780, 430],
  ["mgrandma", "妈妈的妈妈", "外婆", 960, 430],
  // 父母辈
  ["fatherBrother", "爸爸的哥哥", "伯伯", 120, 520],
  ["fatherYoungerBrother", "爸爸的弟弟", "叔叔", 280, 520],
  ["father", "爸爸", "爸爸", 420, 520],
  ["auntFather", "爸爸的妹妹", "姑姑", 620, 520],
  ["auntHusband", "爸爸的妹妹的丈夫", "姑父", 780, 520],
  ["mother", "妈妈", "妈妈", 960, 520],
  ["uncleMother", "妈妈的弟弟", "舅舅", 1120, 520],
  ["auntMother", "妈妈的妹妹", "姨妈", 1060, 720],
  // 同辈（以我为中心展开）
  ["auntSon", "爸爸的妹妹的儿子", "姑表哥", 120, 640],
  ["elderBrother", "哥哥", "哥哥", 280, 640],
  ["youngerBrother", "弟弟", "弟弟", 420, 640],
  ["me", "", "我", 560, 640],
  ["elderSister", "姐姐", "姐姐", 700, 640],
  ["youngerSister", "妹妹", "妹妹", 840, 640],
  ["wife", "老婆", "妻子", 980, 640],
  ["husband", "丈夫", "丈夫", 980, 640],
  ["uncleDaughter", "妈妈的弟弟的女儿", "表姐", 1120, 640],
  // 配偶父母（岳父岳母 / 公公婆婆）
  ["wifeFather", "老婆的爸爸", "岳父", 860, 730],
  ["wifeMother", "老婆的妈妈", "岳母", 1020, 730],
  ["husbandFather", "丈夫的爸爸", "公公", 860, 820],
  ["husbandMother", "丈夫的妈妈", "婆婆", 1020, 820],
  // 配偶兄弟姐妹
  ["brotherInLaw", "老婆的弟弟", "小舅子", 1180, 730],
  ["sisterInLaw", "老婆的妹妹", "小姨子", 1180, 820],
  ["husbandBrother", "丈夫的弟弟", "小叔子", 1180, 910],
  ["husbandSister", "丈夫的姐姐", "大姑姐", 1180, 1000],
  // 子女辈
  ["son", "儿子", "儿子", 360, 820],
  ["daughter", "女儿", "女儿", 520, 820],
  ["daughterInLaw", "儿子的老婆", "儿媳", 680, 820],
  ["sonInLaw", "女儿的丈夫", "女婿", 840, 820],
  // 孙辈
  ["grandson", "儿子的儿子", "孙子", 300, 910],
  ["granddaughter", "儿子的女儿", "孙女", 460, 910],
  ["mGrandson", "女儿的儿子的儿子", "外孙", 620, 910],
  ["mGranddaughter", "女儿的女儿", "外孙女", 780, 910],
  // 曾孙 · 玄孙
  ["ggs", "儿子的儿子的儿子", "曾孙", 300, 1000],
  ["ggsDaughter", "儿子的儿子的女儿", "曾孙女", 460, 1000],
  ["xgs", "儿子的儿子的儿子的儿子", "玄孙", 300, 1090],
  ["xgsDaughter", "儿子的儿子的儿子的女儿", "玄孙女", 460, 1090]
];

/** 节点副标题 */
const GRAPH_HINTS = {
  tier7p: "父系直系 · 上7代",
  tier6p: "父系直系 · 上6代",
  tier5p: "父系直系 · 上5代",
  tier4p: "父系直系 · 上4代",
  tier3p: "父系直系 · 上3代",
  tier3m: "曾祖父的妻子",
  grandpaBrother: "爷爷的哥哥",
  grandpa: "爸爸的爸爸",
  grandma: "爸爸的妈妈",
  tier3mp: "母系 · 上3代",
  tier3mm: "母系 · 上3代",
  mgrandpa: "妈妈的爸爸",
  mgrandma: "妈妈的妈妈",
  fatherBrother: "爸爸的哥哥",
  fatherYoungerBrother: "爸爸的弟弟",
  father: "我的父亲",
  auntFather: "爸爸的姐妹",
  auntHusband: "姑姑的丈夫",
  mother: "我的母亲",
  uncleMother: "妈妈的兄弟",
  auntMother: "妈妈的姐妹",
  elderBrother: "我的哥哥",
  youngerBrother: "我的弟弟",
  elderSister: "我的姐姐",
  youngerSister: "我的妹妹",
  me: "查询起点",
  wife: "我的妻子",
  husband: "我的丈夫",
  wifeFather: "妻子的爸爸",
  wifeMother: "妻子的妈妈",
  husbandFather: "丈夫的爸爸",
  husbandMother: "丈夫的妈妈",
  auntSon: "姑姑一侧晚辈",
  uncleDaughter: "舅舅一侧晚辈",
  brotherInLaw: "妻子的弟弟",
  sisterInLaw: "妻子的妹妹",
  husbandBrother: "丈夫的弟弟",
  husbandSister: "丈夫的姐姐",
  son: "我的儿子",
  daughter: "我的女儿",
  daughterInLaw: "儿子的妻子",
  sonInLaw: "女儿的丈夫",
  grandson: "儿子的儿子",
  granddaughter: "儿子的女儿",
  mGrandson: "女儿的外孙",
  mGranddaughter: "女儿的外孙女",
  ggs: "儿子的孙子",
  ggsDaughter: "儿子的孙女",
  xgs: "孙子的儿子",
  xgsDaughter: "孙子的孙女"
};

/** 按性别隐藏不适用节点，避免配偶/姻亲重叠 */
const GRAPH_HIDDEN_BY_SEX = {
  1: ["husband", "husbandBrother", "husbandSister", "husbandFather", "husbandMother"],
  0: ["wife", "brotherInLaw", "sisterInLaw", "wifeFather", "wifeMother"]
};

const GRAPH_VIEWBOX = { width: 1280, height: 1160 };

const GRAPH_LINKS = [
  ["tier7p", "tier6p"],
  ["tier6p", "tier5p"],
  ["tier5p", "tier4p"],
  ["tier4p", "tier3p"],
  ["tier3p", "tier3m"],
  ["tier3p", "grandpa"],
  ["grandpa", "grandpaBrother"],
  ["grandpa", "grandma"],
  ["grandpa", "father"],
  ["grandma", "father"],
  ["tier3mp", "mgrandpa"],
  ["tier3mm", "mgrandma"],
  ["mgrandpa", "mgrandma"],
  ["mgrandpa", "mother"],
  ["mgrandma", "mother"],
  ["father", "fatherBrother"],
  ["father", "fatherYoungerBrother"],
  ["father", "auntFather"],
  ["auntFather", "auntHusband"],
  ["mother", "uncleMother"],
  ["mother", "auntMother"],
  ["father", "me"],
  ["mother", "me"],
  ["me", "wife"],
  ["me", "husband"],
  ["wife", "wifeFather"],
  ["wife", "wifeMother"],
  ["husband", "husbandFather"],
  ["husband", "husbandMother"],
  ["me", "elderBrother"],
  ["me", "youngerBrother"],
  ["me", "elderSister"],
  ["me", "youngerSister"],
  ["auntFather", "auntSon"],
  ["uncleMother", "uncleDaughter"],
  ["wife", "brotherInLaw"],
  ["wife", "sisterInLaw"],
  ["husband", "husbandBrother"],
  ["husband", "husbandSister"],
  ["me", "son"],
  ["me", "daughter"],
  ["son", "daughterInLaw"],
  ["daughter", "sonInLaw"],
  ["son", "grandson"],
  ["son", "granddaughter"],
  ["daughter", "mGrandson"],
  ["daughter", "mGranddaughter"],
  ["grandson", "ggs"],
  ["granddaughter", "ggsDaughter"],
  ["ggs", "xgs"],
  ["ggsDaughter", "xgsDaughter"]
];
